name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore repos/casestudy_devops/
      - name: Build and test
        run: dotnet build --configuration Release repos/casestudy_devops/ && dotnet test repos/casestudy_devops/
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: repos/casestudy_devops/casestudy_devops/bin/Release/net6.0-windows/casestudy_devops.exe
