name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    working-directory: \repos\casestudy_devops\
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore 
    - name: Build and test
      run: dotnet build --configuration Release && dotnet test
    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: bin/Release
